openapi: 3.0.0
info:
  description: GraphSense API
  title: GraphSense API
  version: 0.4.4
servers:
  - url: 'http://openapi_server:9000'
paths:
  /stats:
    get:
      operationId: get_statistics
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/stats'
      summary: Get statistics of supported currencies
      tags:
      - general
  /{currency}/blocks:
    get:
      operationId: list_blocks
      parameters:
        - $ref: '#/components/parameters/currency' 
        - $ref: '#/components/parameters/page'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blocks'
      summary: Get all blocks
      tags:
      - blocks
  /{currency}/blocks/{height}:
    get:
      operationId: get_block
      parameters:
        - $ref: '#/components/parameters/currency' 
        - $ref: '#/components/parameters/height'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/block'
      summary: Get a block by its height
      tags:
      - blocks
  /{currency}/blocks/{height}/txs:
    get:
      operationId: list_block_txs
      parameters:
        - $ref: '#/components/parameters/currency' 
        - $ref: '#/components/parameters/height'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/block_txs'
      summary: Get all blocks (100 per page)
      tags:
      - blocks

  /{currency}/blocks/{height}/txs.csv:
    get:
      operationId: list_block_txs_csv
      parameters:
        - $ref: '#/components/parameters/currency' 
        - $ref: '#/components/parameters/height'
      responses:
        "200":
          description: OK
          content:
            text/csv: 
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/block_tx_summary'
      summary: Get all blocks as CSV
      tags:
      - blocks
  /{currency}/addresses/{address}:
    get:
      operationId: get_address_with_tags
      parameters:
        - $ref: '#/components/parameters/currency' 
        - $ref: '#/components/parameters/address' 
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/address'
      summary: Get an address with tags
      tags:
      - addresses
components:
  parameters:
    currency:
      in: path
      name: currency
      required: true
      schema:
        type: string
        format: string
      description: The cryptocurrency (e.g., btc)
      example: 'btc'
    height:
      in: path
      name: height
      required: true
      schema:
        type: integer
        minimum: 1
      description: The block height
      example: 1
    page:
      in: query
      name: page
      required: false
      schema:
        type: string
      description: Resumption token for retrieving the next page
      example: 0400030bff00f07fffff9b00
    address:
      in: path
      name: address
      required: true
      schema:
        type: string
        format: string
      description: The cryptocurrency address
      example: '3Hrnn1UN78uXgLNvtqVXMjHwB41PmX66X4'
  schemas:
    stats:
      type: object
      properties:
        currencies:
          type: array
          items:
            $ref: '#/components/schemas/currency_stats'
       # TODO add tools, notes, data_sources?
    currency_stats:
      title: statistics of a cryptocurrency
      type: object
      properties:
        name:
          type: string
        no_blocks:
          format: int64
          type: integer
        no_address_relations:
          format: int64
          type: integer
        no_addresses:
          format: int64
          type: integer
        no_entities:
          format: int64
          type: integer
        no_txs:
          format: int64
          type: integer
        no_labels:
          format: int64
          type: integer
        timestamp:
          format: int64
          type: integer
    block:
      type: object
      properties:
        block_hash:
          type: string
          format: string
        height: 
          format: int64
          type: integer
          minimum: 1
        no_txs: 
          format: int64
          type: integer
        timestamp: 
          format: int64
          type: integer
    block_txs:
      type: object
      properties:
        height: 
          type: integer
        txs:
          type: array
          items:
            $ref: '#/components/schemas/block_tx_summary'
    block_tx_summary:
      type: object
      properties:
        tx_hash: 
          type: string
        no_inputs: 
          type: integer
          format: int64
        no_outputs:
          type: integer
          format: int64
        total_input:
          $ref: '#/components/schemas/values'
        total_output:
          $ref: '#/components/schemas/values'
    blocks:
      type: object
      properties:
        next_page: 
          $ref: '#/components/schemas/next_page'
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/block'
    address:
      type: object
      required:
        - address
        - balance
        - first_tx
        - last_tx
        - in_degree
        - out_degree
        - no_incoming_txs
        - no_outgoing_txs
        - total_received
        - total_spent
      properties:
        address: 
          type: string
          description: Address
        balance: 
          $ref: '#/components/schemas/values'
        first_tx: 
          $ref: '#/components/schemas/tx_summary'
        last_tx: 
          $ref: '#/components/schemas/tx_summary'
        in_degree: 
          type: integer
          format: int64
        out_degree: 
          type: integer
          format: int64
        no_incoming_txs: 
          type: integer
          format: int64
        no_outgoing_txs: 
          type: integer
          format: int64
        total_received: 
          $ref: '#/components/schemas/values'
        total_spent: 
          $ref: '#/components/schemas/values'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/tag'
          description: Tags
    tx_summary:
        type: object
        required:
          - height
          - timestamp
          - tx_hash
        properties:
          height: 
            type: integer
            format: int64
            description: Transaction height
          timestamp:
            type: integer
            format: int64
            description: Transaction timestamp
          tx_hash:
            type: string
            description: Transaction hash
    tag:
        type: object
        properties:
          label:
              type: string


    values:
      type: object
      properties:
        eur:
          type: integer
          format: int64
        usd:
          type: integer
          format: int64
        value:
          type: integer
          format: int64
    next_page:
      type: string
      format: string





