openapi: 3.0.0
info:
  description: GraphSense API
  title: GraphSense API
  version: 0.4.4
servers:
  - url: http://openapi_server:9000

paths:
  /{currency}/stats:
    $ref: '/spec/paths/stats.yaml'
  /{currency}/blocks:
    $ref: '/spec/paths/blocks.yaml'
  /{currency}/blocks/{height}:
    $ref: '/spec/paths/block.yaml'
  /{currency}/blocks/{height}/txs:
    $ref: '/spec/paths/block_txs.yaml'
  /{currency}/blocks/{height}/txs.csv:
    $ref: '/spec/paths/block_txs_csv.yaml'


